SET(ZERO_LIB_PATH ${ZERO_SDK_PATH}/zero-lib)
SET(ZERO_LIB_INCLUDE_DIR
    ${ZERO_LIB_PATH}/include
)

SET(COMMON_SOURCE_DIR ${ZERO_LIB_PATH}/common)
SET(BUS_SOURCE_DIR ${ZERO_LIB_PATH}/bus)
SET(CHIP_SOURCE_DIR ${ZERO_LIB_PATH}/chip)
SET(MODULE_SOURCE_DIR ${ZERO_LIB_PATH}/module)

AUX_SOURCE_DIRECTORY(${COMMON_SOURCE_DIR} COMMON_SOURCES)
AUX_SOURCE_DIRECTORY(${BUS_SOURCE_DIR} BUS_SOURCES)
AUX_SOURCE_DIRECTORY(${CHIP_SOURCE_DIR} CHIP_SOURCES)
AUX_SOURCE_DIRECTORY(${MODULE_SOURCE_DIR} MODULE_SOURCES)

SET(ZERO_LIB_SOURCES
    ${COMMON_SOURCES}
    ${BUS_SOURCES}
    ${CHIP_SOURCES}
    ${MODULE_SOURCES}
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(ZeroLib DEFAULT_MSG ZERO_LIB_INCLUDE_DIR ZERO_LIB_SOURCES)
